version: '3.1'
services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ../mysqlFabLog:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080
  